import { useEffect, useState } from 'react'
import { api } from '../lib/api'

const STATUS_STYLES = {
  VALID: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  REVOKED: 'bg-rose-100 text-rose-800 border-rose-200',
  TAMPERED: 'bg-amber-100 text-amber-800 border-amber-200',
  PENDING_ANCHOR: 'bg-sky-100 text-sky-800 border-sky-200',
  CHAIN_UNAVAILABLE: 'bg-orange-100 text-orange-800 border-orange-200',
  NOT_FOUND: 'bg-slate-100 text-slate-700 border-slate-300',
}

function statusStyle(status) {
  return STATUS_STYLES[status] || STATUS_STYLES.NOT_FOUND
}

function formatClockTime(value) {
  const parsed = Date.parse(value)
  if (Number.isNaN(parsed)) {
    return value
  }
  return new Date(parsed).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
}

function freshnessText(checkedAt) {
  if (!checkedAt) {
    return 'Verified time unavailable'
  }

  const parsed = Date.parse(checkedAt)
  if (Number.isNaN(parsed)) {
    return `Verified at ${checkedAt}`
  }

  const delta = Math.max(0, Date.now() - parsed)
  if (delta <= 15_000) {
    return 'Verified just now'
  }

  return `Verified at ${formatClockTime(checkedAt)}`
}

function buildSummary(response) {
  const status = response?.verificationStatus || 'NOT_FOUND'
  const headline = response?.verdictHeadline || 'No verification record found for this reference.'
  const issuer = response?.issuer || 'Unknown issuer'
  const checkedAt = response?.checkedAt || 'N/A'
  const credentialHash = response?.credentialHash || 'N/A'
  const txHash = response?.txHash || 'N/A'
  const explanation = response?.explanation || 'No additional notes.'

  return [
    'Verification generated by BlockCred',
    `Status: ${status} (${headline})`,
    'Reference: token-based verification',
    `Issuer: ${issuer}`,
    `CheckedAt: ${checkedAt}`,
    `CredentialHash: ${credentialHash}`,
    `TxHash: ${txHash}`,
    `Note: ${explanation}`,
  ].join('\n')
}

export default function PublicVerifyPage() {
  const token = new URLSearchParams(window.location.search).get('t') || ''

  const [loading, setLoading] = useState(true)
  const [response, setResponse] = useState(null)
  const [networkMessage, setNetworkMessage] = useState('')
  const [copyMessage, setCopyMessage] = useState('')

  useEffect(() => {
    const controller = new AbortController()
    let active = true

    async function run() {
      setLoading(true)
      setNetworkMessage('')
      setCopyMessage('')

      try {
        const result = await api.publicVerifyToken(token, { signal: controller.signal })
        if (!active || controller.signal.aborted) {
          return
        }
        setResponse(result)
      } catch {
        if (!active || controller.signal.aborted) {
          return
        }
        setNetworkMessage('Unable to complete verification right now. Please retry shortly.')
      } finally {
        if (active && !controller.signal.aborted) {
          setLoading(false)
        }
      }
    }

    run()

    return () => {
      active = false
      controller.abort()
    }
  }, [token])

  async function copySummary() {
    if (!response) {
      return
    }

    try {
      await navigator.clipboard.writeText(buildSummary(response))
      setCopyMessage('Verification summary copied.')
    } catch {
      setCopyMessage('Unable to copy summary.')
    }
  }

  return (
    <div className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-3xl space-y-5">
        <header className="rounded-2xl border border-slate-200 bg-white p-6">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">BlockCred</p>
          <h1 className="mt-2 text-2xl font-bold text-slate-900">Credential Verification</h1>
          <p className="mt-1 text-sm text-slate-600">Verification result for employer reference.</p>
        </header>

        {loading ? (
          <section className="rounded-2xl border border-slate-200 bg-white p-6">
            <p className="text-sm font-medium text-slate-700">Verifying credential against issuer and blockchain records…</p>
          </section>
        ) : null}

        {!loading && networkMessage ? (
          <section className="rounded-2xl border border-slate-200 bg-white p-6">
            <p className="text-sm text-slate-700">{networkMessage}</p>
          </section>
        ) : null}

        {!loading && response ? (
          <>
            <section className="rounded-2xl border border-slate-200 bg-white p-6">
              <div className="mb-3 flex flex-wrap items-center gap-3">
                <span className={`inline-flex rounded-full border px-3 py-1 text-xs font-semibold tracking-wide ${statusStyle(response.verificationStatus)}`}>
                  {response.verificationStatus}
                </span>
                <span className="text-xs uppercase tracking-wide text-slate-500">{freshnessText(response.checkedAt)}</span>
              </div>
              <h2 className="text-xl font-bold text-slate-900">{response.verdictHeadline}</h2>
              <p className="mt-1 text-sm text-slate-700">{response.decisionHint}</p>
            </section>

            <section className="rounded-2xl border border-slate-200 bg-white p-6">
              <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide text-slate-500">Evidence</h3>
              <div className="grid gap-3 sm:grid-cols-2">
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Issuer</p>
                  <p className="text-sm text-slate-800">{response.issuer || 'Unknown issuer'}</p>
                </div>
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Blockchain confirmation</p>
                  <p className="text-sm text-slate-800">{response.blockchainConfirmation}</p>
                </div>
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Checked at</p>
                  <p className="text-sm text-slate-800">{response.checkedAt || 'N/A'}</p>
                </div>
                <div>
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Credential hash</p>
                  <p className="break-all font-mono text-xs text-slate-800">{response.credentialHash || 'N/A'}</p>
                </div>
              </div>

              <div className="mt-4 border-t border-slate-200 pt-4">
                <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Explanation</p>
                <p className="text-sm text-slate-700">{response.explanation}</p>
              </div>

              <div className="mt-4 flex flex-wrap items-center gap-3">
                {response.txExplorerUrl ? (
                  <a
                    href={response.txExplorerUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="text-xs font-medium text-slate-500 underline decoration-slate-300 underline-offset-2 hover:text-slate-700"
                  >
                    View technical transaction record
                  </a>
                ) : null}

                <button
                  type="button"
                  onClick={copySummary}
                  className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-100"
                >
                  Copy verification summary
                </button>

                {copyMessage ? <span className="text-xs text-slate-500">{copyMessage}</span> : null}
              </div>
            </section>
          </>
        ) : null}
      </div>
    </div>
  )
}
