CREATE TABLE IF NOT EXISTS credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id VARCHAR(255) NOT NULL UNIQUE,
    hash VARCHAR(128) NOT NULL UNIQUE,
    lifecycle_status VARCHAR(64) NOT NULL,
    canonical_payload_json VARCHAR(3000) NOT NULL,
    last_tx_hash VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_credentials_credential_id ON credentials (credential_id);
CREATE INDEX IF NOT EXISTS idx_credentials_hash ON credentials (hash);

CREATE TABLE IF NOT EXISTS anchor_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id VARCHAR(255) NOT NULL,
    hash VARCHAR(255) NOT NULL,
    job_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    retry_count INTEGER NOT NULL,
    next_run_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_attempt_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(2000),
    failure_code VARCHAR(64),
    last_manual_trigger_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_anchor_jobs_cred ON anchor_jobs (credential_id);
CREATE INDEX IF NOT EXISTS idx_anchor_jobs_cred_type_created ON anchor_jobs (credential_id, job_type, created_at);
CREATE INDEX IF NOT EXISTS idx_anchor_jobs_status_next_id ON anchor_jobs (status, next_run_at, id);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(255) NOT NULL,
    credential_id VARCHAR(255) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    category VARCHAR(32) NOT NULL,
    request_id VARCHAR(255),
    details VARCHAR(4000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_cred_created ON audit_logs (credential_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_action_created ON audit_logs (action, created_at);

CREATE TABLE IF NOT EXISTS system_controls (
    control_key VARCHAR(120) PRIMARY KEY,
    control_value VARCHAR(2000) NOT NULL,
    updated_by VARCHAR(255),
    details VARCHAR(2000),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_digests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest_date DATE NOT NULL UNIQUE,
    record_count INTEGER NOT NULL,
    digest_hex VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_digests_date ON audit_digests (digest_date);
CREATE INDEX IF NOT EXISTS idx_audit_digests_created ON audit_digests (created_at);
